apiVersion: v1
kind: Namespace
metadata:
  name: processing

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connection-config
  namespace: processing
data:
  kafka_bootstrap_servers: "kafka-broker-0.kafka-cluster.svc.cluster.local:9092,kafka-broker-1.kafka-cluster.svc.cluster.local:9092,kafka-broker-2.kafka-cluster.svc.cluster.local:9092" # Ersetze dies mit deiner tatsächlichen Kafka-Verbindungszeichenkette

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      nodeSelector:
        kubernetes.io/hostname: aks-perf-25433128-vmss000003
      containers:
        - name: simulator
          image: ghcr.io/joystick01/coolersimulator:0.1.4
          resources:
            limits:
              cpu: "2"
              memory: "8Gi"
          env:
            - name: ERROR_RATE
              value: "1000"
            - name: DUPLICATE_RATE
              value: "1000"
            - name: PAYLOAD_WRITER_TYPE
              value: "KAFKA"
            - name: PAYLOAD_WRITER_OFFSET
              value: "0"
            - name: KAFKA_PAYLOAD_WRITER_TOPIC
              value: "ingress"
            - name: KAFKA_PAYLOAD_WRITER_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-connection-config
                  key: kafka_bootstrap_servers
            - name: KAFKA_PAYLOAD_WRITER_FLOOD_MESSAGES
              value: "31449600" # Ersetze dies mit der berechneten Rate
            - name: KAFKA_PAYLOAD_WRITER_SEND_RATE
              value: "52" # Ersetze dies mit deinem gewünschten Send Rate Wert

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
  namespace: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      nodeSelector:
        kubernetes.io/hostname: aks-perf-25433128-vmss000003      # Ersetze dies mit dem Namen des Nodes für den Prozessor
      containers:
        - name: processor
          image: ghcr.io/joystick01/messageprocessingservice:0.1.1
          env:
            - name: APPLICATION_ID_CONFIG
              value: "MessageProcessingService"
            - name: BOOTSTRAP_SERVERS_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: kafka-connection-config
                  key: kafka_bootstrap_servers
            - name: INPUT_TOPIC
              value: "ingress"
            - name: OUTPUT_TOPIC
              value: "egress"